POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Impvb3N0amUxMjMiLCJpZCI6IjYzZThkYmJhMDA3NTE3ZTY2NjcyYmEzNSIsImlhdCI6MTY3NjIwNjM4OH0.WiXVeufWiW1ABVlJ9ZYoHVEJTmf8RbOq5IN8LK-nr8A

{
    "title": "sample",
    "author": "joost",
    "url": "https://google.com",
    "likes": 12
}