POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json

{
    "title": "sample",
    "author": "Wed, 21 Oct 2015 18:27:50 GMT",
    "url": "https://google.com",
    "likes": 12
}