POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaGFuIiwiaWQiOiI2M2U4ZWY3MTQyOTcxMWJlMmJiMTc3NTAiLCJpYXQiOjE2NzYyMTAwNDJ9.TfK3LNUd6MlItHYXFQNeRgFgemXYvLghlC5ckZdhUnk

{
    "title": "sample",
    "author": "joost",
    "url": "https://google.com",
    "likes": 12
}