DELETE http://localhost:3003/api/blogs/63e8f06c429711be2bb1775b HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaGFuIiwiaWQiOiI2M2U4ZWY3MTQyOTcxMWJlMmJiMTc3NTAiLCJpYXQiOjE2NzYyMTAzODd9.GrGDf_DFze2hLlw9lUVkoEjAw8EP9mknxstbvAkVib0